version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:alpine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependences
          command: npm i

      # Save cache for next run
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: check build for errors
          command: npm run build

      - run:
          name: check code style
          command: npm run lint

      - run:
          name: test
          command: npm run test -- --coverage

      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
